// USER STATUS
export const USER_LOADED = 'USER_LOADED';
export const USER_READY = 'USER_READY';
export const INITIAL_STATE = 'UNKNOW';

// CATEGORY STATUS
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED';

// PRODUCT STATUS
export const PRODUCTS_LOADED = 'PRODUCTS_LOADED';